Dev
rerum-nn/neural-net pull request #2
Opened 2024-01-17 19:09 UTC by rerum-nn

I realized late that I needed to use Eigen

2024-01-20 19:47 UTC, DimaTrushin requested changes
Обрати внимание, что если я делал замечание, то потом надо по аналогии все подобные места исправить. Я не повторялся при похожих ошибках.

У тебя какой-то пиздец творится с дизайном для apply. Переделай по нормальному, ты приобрел кучу геморроя и лишнии аллокации памяти.

Кроме того, я написал как изменить использование рандома.

Ты по как-то убого инициализируешь слои случайными данными при вычислении в нейросети. Это пиздец. Убери и напиши по-нормальному.

2024-01-20 19:47 UTC, DimaTrushin commented on src/ActivationFunctions/ActivationFunction.h
> +    const ActivationConcept* operator->() const {
Вот это прям очень правильно пробросить const.

2024-01-20 19:47 UTC, DimaTrushin commented on src/ActivationFunctions/ActivationFunction.h
> +    }
1) Вот этот код у тебя упадет.
2) Дупликация кода.
Ты не предусмотрел пустой объект, который возникает, когда из него мувнули данные. Надо вот так
```cpp
ActivationFunction(const ActivationFunction& other)
  : object_((other.object_ ? other.object_->Clone() : nullptr)) {
}
ActivationFunction& operator=(const ActivationFunction& other) {
    return *this = ActivationFunction(other);
}
```
3) Хорошо бы еще добавить оператор проверки есть ли данные в контейнере конвертацией к bool например через operator bool() const.

2024-01-20 19:47 UTC, DimaTrushin commented on src/ActivationFunctions/ActivationFunction.h
> +
У тебя объект не мувабл. Надо добавить дефолтные мувы так
```cpp
ActivationFunction(ActivationFunction&&) noexcept = default;
ActivationFunction& operator=(ActivationFunction&&) noexcept = default;
```

2024-01-20 19:47 UTC, DimaTrushin commented on src/ActivationFunctions/ActivationFunction.h
> +    }
Я бы чуток поменял
```cpp
template <typename ActivationT>
ActivationFunction(ActivationT&& func)
  : object_(std::make_unique<ActivationModel<ActivationT>>(std::forward<ActivationT>(func))) {
}
```
Это дешевле на один мув, а трудов почти никаких. Я понял, что совет от Sean Parent по поводу sinking arguments, не лучшее решение. Есть ситуации, где это очень неудобно и плохо работает. Так всегда надежно.

2024-01-20 19:47 UTC, DimaTrushin commented on src/LinearPrimitives.h
Плохое название. Это примитивы не линейного класса, а вообще общие типы, которые используются в проекте.

2024-01-20 19:47 UTC, DimaTrushin commented on src/LinearPrimitives.h
> +#include <vector>
убрать лишние инклуды.

2024-01-20 19:47 UTC, DimaTrushin commented on src/ActivationFunctions/Sigmoid.cpp
> +    return jacobian;
В Eigen есть метод asDiagonal для построения диагональных матриц.

2024-01-20 19:47 UTC, DimaTrushin commented on src/ActivationFunctions/Sigmoid.cpp
> +                  [](double& d) { d = 1. / (1. + std::exp(-d)); });
Такой подход означает, что ты сначала должен зарезервировать вектор нужного размера, а потом прям на месте применить к нему метод. Вместо простого вызова
```cpp
Vector result = sigmoid.Applay(data);
```
тебе придется писать
```cpp
Vector result(size);
sigmoid.Applay(&result);
```
Или ты как-то жестко переиспользуешь память и у тебя нет новых аллокаций даже при создании новых векторов? Но я что-то сомневаюсь.

2024-01-20 19:47 UTC, DimaTrushin commented on src/ActivationFunctions/Sigmoid.cpp
> +Matrix Sigmoid::Derivative(const Vector& values) const {
Странно, что clang-formant не ругнулся на отсутствие пустой строки между функциями. Или ты не применял его?

2024-01-20 19:47 UTC, DimaTrushin commented on src/Layer.h
> +    void NormalRandomInit(int seed = std::random_device()());
1) Уже название метод говорит о том, что его быть тут не должно ни в каком виде. Эту работу должен делать конструктор, либо это приватный метод в конструкторе, который не должен быть доступен пользователю.
2) Что плохо, что у этого метода нет явной зависимости от данных. Он по сути совершает манипуляцию над состоянием объекта. Лучше не так, я прокомментирую конструктор в cpp файле.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Layer.cpp
> +void Layer::NormalRandomInit(int seed) {
Ууу, у тебя эта функция даже не зовется в конструкторе, это плохо.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Layer.cpp
> +    Eigen::Rand::P8_mt19937_64 generator(seed);
Это вообще не случайное задание. Каждый вызов функции с одним и тем же сидом дает один и тот же результат. Потому тебе нужен генератор сидов, чтобы добиться хоть какой-то случайности между вызовами этой функции. Это очень плохо. Делать надо не так. Тебе надо сделать класс Random, который инициализирует все что надо и предоставляет нужные методы по генерации. А потом надо сделать его Scott Meyers Singleton и обращаться к нему глобально.

Сделай так
```cpp
class Random {
public:
  Random(int seed);
  Matrix normal(Index rows, Index columns);
private:
  static constexpr int k_default_seed_ = 42;
  Eigen::Rand::P8_mt19937_64 generator_ = k_default_seed_;
};
```
И потом его уже закрываешь в глобальный объект так
```cpp
class GlobalRandom {
public:
  Random& access() {
    static Random;
    return Random;
  }
};
```
И потом можешь подключать в cpp файлы хедер с GlobalRandom и вызывать его так
```cpp
Layer::Layer(size_t input, size_t output, ActivationFunction func)
  : weights_(GlobalRandom::normal(output, input)),
    bias_(GlobalRandom::normal(output, 1)),
    activation_func_(std::move(func)) {}
```

Тут есть еще вопрос как инициализировать этого товарища. Можно сделать так:
```cpp
class GlobalRandom {
public:
  static constexpr int k_default_seed = 42;
  Random& access(int seed = k_default_seed) {
    static Random = k_defaul_seed;
    return Random;
  }
};
```
Тогда чтобы инициализировать его надо в самый первый вызов написать
```cpp
int main() {
  GlobalRandom::access(24);
  run_all_tests();
  return 0;
}
```
С этим подходом есть проблемы, что он не гарантирует, что ты где-то до этого не обратился и не сделал дефолтный сид. Это фиксится, но это уже отдельный разговор. Можешь у меня в Library репозитории посмотреть Singleton папку с примером того, что я делаю и проект Typing Analysis с примером использования например для глобального таймера. В диздоке все описано.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Layer.cpp
> +    *input_vector = weights_ * *input_vector + bias_;
1) Ну и в чем смысл это делать? Если ты даже не inplace делаешь модификации? Что мешало сделать
```cpp
Vector Layer::Forward(const Vector& input) const {
  return activation_function_->Applay(weights_ * input + bias_);
}
```
И все.
2) Еще проблема в том, что ты гадишь данные, которые лежали в input_vector. Тебе всегда их надо будет копировать. Это уже потенциально дорого.
3) У тебя переменная input_vector не отражает смысла она и входная и выходная переменная. В  общем. Уберай это говно и пиши по нормальному.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Layer.h
> +#include <memory>
Убери лишние хедеры. И вообще хорошо свои хеддеры включать до сторонних библиотек, а уже после них stl. Так ты отловишь если ты забыл нужные хедеры куда-то добавить. И не надо пихать лишние зависимости. Время компиляции имеет значение.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Layer.h
> +#include <random>
Этот тоже уйдет. Тебе по хорошему вообще не надо никакой рандом подключать в хедер. Это лишь деталь имплементации, которая будет использована в cpp.

2024-01-20 19:47 UTC, DimaTrushin commented on src/LossFunctions/LossFunction.h
> +// TODO: rewrite to Type Erasure idiom
На самом деле ты можешь не париться с type erasure. Хотя ты крут, что написал. Можно просто хранить две std::function или даже два указателя на функции в теле класса. Но никогда не пиши виртуальные функции.

2024-01-20 19:47 UTC, DimaTrushin commented on src/LossFunctions/MSE.h
> +class MSE : LossFunction {
Если уж наследуешься от интерфейса, то хотя бы публично. Иначе у тебя нет возможности к нему кастануться.

2024-01-20 19:47 UTC, DimaTrushin commented on src/LossFunctions/MSE.cpp
> +    }
Нужная функция уже есть в Eigen.

2024-01-20 19:47 UTC, DimaTrushin commented on src/LossFunctions/MSE.cpp
> +                   [](double d1, double d2) { return d2 - d1; });
1) А что мешало написать
```cpp
return expected - present;
```
???
2) Ты забыл 2-ку, должно быть
```cpp
return 2 * (expected - present);
```

2024-01-20 19:47 UTC, DimaTrushin commented on src/Network.h
> +    Vector Predict(const std::initializer_list<double>& input_data);
Плохая тема. Лучше сделай один метод Predict с единым интерфейсом и просто строй сначала данные в том формате, которые сеть сможет съесть.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Network.cpp
> +    }
Если кто-то задал меньше двух размеров, то это ты. А значит тебе надо исправить этот баг. Его надо ловить assert-ом. Потому что это precondition для конструктора. Не лови свои ошибки исключениями.
Вот хороший пример для исключения. Ты пытаешься подключиться к драйверу и система не дает. Или ты пытаешься прочитать из файла и такого файла нет или система не дает и ты не можешь продолжить конструировать объект. Свои же ошибки не надо ловить исключениями.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Network.cpp
> +            "sizes of list of sizes and list of activation functions are not equal");
Это опять preconsition, тут лучше assert.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Layer.h
> +    Layer(size_t input, size_t output, ActivationFunction func);
Не используй сырые типы вроде size_t. Дело в том, что Eigen использует тип Eigen::Index для того чтобы менеджерить размеры контейнеров и индексы. И самое страшное, что этот тип знаковый (скорее всего int). А сравнение знаковых и беззнаковых типов это UB. Потому не используй тут сырые size_t. Лучше добавь глобальный using вида
```cpp
using Index = Eigen::Index;
```
И пользуйся только им везде для индексации и размеров. Но проверяй, что он больше нуля например.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Layer.cpp
> +    : weights_(output, input), bias_(output), activation_func_(std::move(func)) {
Размеры 0 у тебя допустимы?

2024-01-20 19:47 UTC, DimaTrushin commented on src/Network.cpp
> +        layer.NormalRandomInit();
Что за дичь? Какого черта у тебя при каждом вызове случайно инициализируются веса? Тут просто надо проащить result по всем слоям.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Network.cpp
> +    Vector res(input_data);
Это тебе никак не помогает, это лишняя реаллокация. У тебя потом оператор присваивания эту память не переиспользует. И кроме того, выход нейросети имеет другой размер, не такой как вход. Это ошибка дизайна.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Network.cpp
> +    for (Layer& layer : layers_) {
тут должно быть обращение по константной ссылке.

2024-01-20 19:47 UTC, DimaTrushin commented on src/Network.cpp
> +Vector Network::Predict(const std::initializer_list<double>& input_data) {
Убрать.

2024-01-20 21:38 UTC, rerum-nn commented on src/ActivationFunctions/ActivationFunction.h
> +        virtual ~ActivationConcept() = default;
Конструктор копирования ActivationFunction ругается, что std::unique_ptr не может вызвать приватный конструктор, при вызове метода Clone
![image](https://github.com/rerum-nn/neural-net/assets/65449805/f1db1153-5aa6-48e2-a577-4a484f4d9d4f)

2024-01-20 22:38 UTC, rerum-nn commented on src/Network.cpp
> +        layer.NormalRandomInit();
Это было оставлено для теста кода, забыл убрать(

2024-04-22 17:27 UTC, rerum-nn commented
Из TODO:
-- Оформить нормально Cmakelist, протестить на gcc и прочие флаги и настройки сделать (сделать настройку для включения выключения OpenMP + настройка количества ядер для его работы).
-- Дописать тесты

2024-05-15 09:00 UTC, DimaTrushin commented on tests/test_deserialize.cpp
> +int main(int argc, char* argv[]) {
У тебя не отключены exception, потому надо поставить блок на них. Это делается так
```cpp
#include "NeuralNetwork.h"
#include "Except.h"

int main() {
  try {
    nn::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```
Обрати внимание, что main не выполняет никакую конкретную работу, она делегирует всю работу другим модулям и защищает ос от утечки в нее исключений и ошибок, чтобы не путать их с ошибками ос. То есть ее задача -- оркестровка на самом высоком уровне.

2024-05-15 09:00 UTC, DimaTrushin commented on tests/test_deserialize.cpp
> +using namespace neural_net;
я бы это поместил в начало main.

2024-05-15 09:01 UTC, DimaTrushin commented on tests/mnist.cpp
> +#ifdef _OPENMP
Вот такое лучше заворачивать в имплементацию а тут звать просто функцию, которая внутри содержит такой код. Плохо использовать в бизнес логике препроцессор.

2024-05-15 09:03 UTC, DimaTrushin commented on src/Utils/Timer.cpp
> +double Timer::Elapsed() const {
Я бы добавил в название метода Milliseconds, чтобы было понятно что ты сразу в этих единицах получаешь время.

2024-05-15 09:04 UTC, DimaTrushin commented on src/Utils/DataManipulate.cpp
> +        Activation activation = ActivationNone();
А у тебя нет дефолтного конструктора? Один из способов это вылечить -- создать функцию, которая внутри switch возвращает нужную ActivationFunction, а тут написать
```cpp
Activation activation = ActivationFunction::FromName(activation_name);
```
И не надо будет искуственное состояние.

2024-05-15 09:07 UTC, DimaTrushin commented on src/Sequential.h
> +    std::vector<float> Fit(const Matrix& input_data, const Matrix& labels,
Из итерфейса не очень понятно, что тут возвращается как и в методе Evaluate.

2024-05-15 09:09 UTC, DimaTrushin commented on src/Sequential.cpp
> +                std::cout << ' ' << metric.GetName() << ": "
Единственное что мне не нравится, что тут аж 4 вложенных scope. Даже в ядре Linux запрещено более 3. Но в целом функция выглядит ок.

2024-05-15 09:11 UTC, DimaTrushin commented on src/Layers/Activations/Softmax.cpp
> +    os << " softmax ";
Я бы хранил эту штуку в виде статической константы к классе, чтобы потом когда ты будешь десериализовать обратиться к ней. Вдруг ты захочешь это имя оменять. Тогда тебе в любом десереализующем коде надо эту же константу править.

2024-05-15 09:13 UTC, DimaTrushin commented on src/Layers/Activations/Softmax.cpp
> +        exp_data_.col(i) = transformed.col(i) / (sums[i] + kEpsilon);
А есть необходимость в использовании этого kEpsilon? Ты же вычитаешь максимум из всех данных, потому у тебя одна из координат становится 1, а остальные положительные. Потому после такой регуляризации нет вообще необходимости в таком костыле.

2024-05-15 09:13 UTC, DimaTrushin commented on src/Layers/Linear.cpp
> +void Linear::SetWeights(const Matrix& weights, const Vector& bias) {
хорошо бы еще версию от rvalue иметь

2024-05-15 09:16 UTC, DimaTrushin commented on src/Datasets/MNIST/MnistDataset.h
> +    static std::pair<Matrix, Matrix> ReadCsv(const std::string& path);
Не используй std::pair. Заведи структуру с нормальными именами полей. А то не понятно что значат эти поля.

2024-05-15 09:16 UTC, DimaTrushin commented on src/Datasets/MNIST/MnistDataset.h
> +    std::tuple<Matrix, Matrix, Matrix, Matrix> LoadData();
Та же пороблема, что и с std::pair.

2024-05-15 09:18 UTC, DimaTrushin commented on src/Metrics/Metric.h
> +    static Metric BinaryAccuracy(float threshold = 0.5);
Чтобы не указывать одну и ту же константу везде, ты можешь сделать статическую константу с дефолтным значением константы.

2024-09-16 16:53 UTC, merged